title: Daisy Icardi's Portfolio
description: Hello, I am Daisy, a Senior Data Analyst and Junior Data Scientist from Italy
author: Daisy Icardi
theme: minimal
social:
  github: https://github.com/daisy-icardi
  linkedin: https://www.linkedin.com/in/daisy-icardi-6b3893268/
baseurl: /daisy-icardi
